server: 
 port: 9555 


spring: 
 application: 
  name: HYSTRIX-DASHBOARD 

hystrix: 
 dashboard: 
  proxyStreamAllowList: "*" 

management:
  endpoints:
    web:
      exposure:
        include: "*" 
    hystrix: 
        stream: 
          enabled: true 
   