server:
  port: 9002 


spring: 
  application: 
     name: contact-service 


eureka: 
  instance: 
    hostname: localhost 


management:
  endpoints:
    web:
      exposure:
        include: "*" 
    hystrix: 
        stream: 
          enabled: true
